namespace DevLeads.Core.Entities;

/// <summary>
/// A broken or degraded business web asset discovered by the Site rescue scanner: the
/// concrete failing URL, what failed, who appears to own it, and the operator's drafted
/// repair-offer outreach. This is a potential paid-repair lead, kept separate from the
/// discussion-post <see cref="Opportunity"/> pipeline because it comes from active
/// scanning rather than public pay-intent posts.
/// </summary>
public class WebAssetFinding
{
    public long Id { get; set; }

    /// <summary>Probe that surfaced this finding (nullable if the probe was later deleted).</summary>
    public long? ProbeId { get; set; }

    /// <summary>Probe name captured at detection time so history survives probe edits/deletes.</summary>
    public string ProbeName { get; set; } = "";

    /// <summary>Canonical failing URL — the deduplication key for a finding.</summary>
    public string Url { get; set; } = "";

    /// <summary>Host of <see cref="Url"/>, used for grouping and contact discovery.</summary>
    public string Host { get; set; } = "";

    /// <summary>Best guess at the owning business name (page title / host), for the operator to confirm.</summary>
    public string BusinessName { get; set; } = "";

    public WebAssetSeverity Severity { get; set; }
    public WebAssetDetection Detection { get; set; }
    public WebAssetStatus Status { get; set; } = WebAssetStatus.New;

    /// <summary>Last observed HTTP status code (0 when the connection itself failed).</summary>
    public int HttpStatus { get; set; }

    /// <summary>Short human summary of what tripped the probe ("HTTP 500", "matched: Fatal error", "TLS handshake failed").</summary>
    public string Signal { get; set; } = "";

    /// <summary>A trimmed excerpt of the matched error text, as evidence for the operator and the AI.</summary>
    public string Evidence { get; set; } = "";

    /// <summary>Software package fingerprinted on the asset, when detected.</summary>
    public string DetectedSoftware { get; set; } = "";

    /// <summary>Discovered owner contact email, if one was found.</summary>
    public string ContactEmail { get; set; } = "";

    /// <summary>Where the contact came from ("mailto", "contact page", "page text", "manual").</summary>
    public string ContactSource { get; set; } = "";

    // Drafted repair-offer outreach — generated by AI, sent manually by the operator.
    public string OutreachSubject { get; set; } = "";
    public string OutreachBody { get; set; } = "";
    public string OutreachProvider { get; set; } = "";
    public string OutreachModel { get; set; } = "";
    public DateTimeOffset? OutreachGeneratedAt { get; set; }

    public string Notes { get; set; } = "";

    public DateTimeOffset FirstSeenAt { get; set; }
    public DateTimeOffset LastCheckedAt { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }
}
